name: Deploy & Migrate on Master Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Create-rds-and-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check if Instance exists
        id: check-db
        run: |
          if aws rds describe-db-instances --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }} > /dev/null 2>&1; then
            echo "DB_EXISTS=true" >> $GITHUB_ENV
          else
            echo "DB_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create RDS PostgreSQL instance if it doesn't exist yet
        if: env.DB_EXISTS == 'false'
        run: |
          aws rds create-db-instance \
            --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }} \
            --db-instance-class ${{ vars.DB_INSTANCE_CLASS }} \
            --engine postgres \
            --allocated-storage ${{ vars.DB_STORAGE }} \
            --master-username ${{ vars.DB_MASTER_USERNAME }} \
            --master-user-password ${{ secrets.DB_MASTER_PASSWORD }} \
            --backup-retention-period 7 \
            --no-multi-az \
            --db-subnet-group-name ${{ vars.DB_SUBNET_GROUP_NAME }} \
            --publicly-accessible \
            --vpc-security-group-ids ${{ secrets.AWS_SECURITY_GROUP_ID_1 }} ${{ secrets.AWS_SECURITY_GROUP_ID_2 }}

      - name: Wait for AWS to cook
        if: env.DB_EXISTS == 'false'
        run: |
          echo "Waiting for RDS instance to be available..."
          aws rds wait db-instance-available --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }}

      - name: Retrieve endpoint of the RDS instance
        run: |
          ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier ${{ vars.DB_INSTANCE_IDENTIFIER }} --query 'DBInstances[0].Endpoint.Address' --output text)
          echo "RDS_ENDPOINT=$ENDPOINT" >> $GITHUB_ENV

      - name: Create DB if it doesn't already exist.
        run: |
          docker run --rm \
            postgres \
            psql -h ${{ env.RDS_ENDPOINT }} -U ${{ vars.DB_MASTER_USERNAME }} -d postgres -c "SELECT 1 FROM pg_database WHERE datname = '${{ vars.DB_NAME }}';" | grep -q 1 || \
            psql -h ${{ env.RDS_ENDPOINT }} -U ${{ vars.DB_MASTER_USERNAME }} -d postgres -c "CREATE DATABASE ${{ vars.DB_NAME }};"

      - name: Migrate
        run: |
          docker run --rm \
            -v $(pwd)/migrations:/flyway/sql \
            flyway/flyway migrate \
            -url="jdbc:postgresql://${{ env.RDS_ENDPOINT }}:5432/${{ vars.DB_NAME }}" \
            -user=${{ vars.DB_MASTER_USERNAME }} \
            -password=${{ secrets.DB_MASTER_PASSWORD }}
